interactive

Query (empty to exit): 
1 (2011-00-002): Measuring Motivation | TechnoTaste
...*Hello*- I am a doctoral student studying whether or not there is a difference in motivational levels between high school instrumental music students and non instrumental students. I have to choose a measurement instrument and am in need of some input based on someone else's experience with the inst...

Query (empty to exit): 